insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maurizio Howlings', 'Moland', '2002-11-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Raven Gawn', 'Chive', '2012-08-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karlene Rymer', 'Village Green', '2006-06-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Annadiana Gian', 'Homewood', '2013-12-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Wrennie Huckle', 'Doe Crossing', '2002-12-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kial Prynne', 'Elmside', '2010-02-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nettle Gutans', 'Becker', '2014-08-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Charla Sells', 'Shasta', '2001-04-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bev Verheijden', 'Twin Pines', '2020-12-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tab Sandyfirth', 'Logan', '2003-12-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Helga Salvadori', 'Pepper Wood', '2000-04-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Grazia Morfell', 'Kenwood', '2005-04-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Zebulen Rishbrook', 'Grim', '2022-11-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jillayne Yeo', 'Dottie', '2021-02-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Saundra McDonand', 'Pankratz', '2008-12-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maud Jiricka', 'Becker', '2008-11-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Melantha Smalridge', 'Kinsman', '2002-08-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sergeant Ingrem', 'Sycamore', '2015-08-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rodrick Howford', 'Sloan', '2013-01-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Joellyn Khilkov', 'Crowley', '2004-03-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dyan Feechan', 'Division', '2009-08-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Murial Cremer', 'Morrow', '2013-03-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ram Blagburn', 'Annamark', '2003-06-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Allina Smythe', 'Brentwood', '2005-04-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Darcie Utton', 'Spaight', '2015-04-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Donovan Wylie', 'Moulton', '2017-06-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Flo Hassan', 'Forest Dale', '2001-07-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pier Redwin', 'Village', '2005-05-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bogey McBeith', 'Forest Run', '2012-09-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hazel Hayzer', 'Sauthoff', '2022-09-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ram MacAnespie', 'Annamark', '2008-03-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carree Lympenie', 'Westridge', '2009-08-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('John Burtonshaw', 'Moulton', '2010-07-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Drusy Portman', 'Scoville', '2013-03-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gwendolen Mapson', 'Mosinee', '2012-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rhodie Gores', 'Carioca', '2005-03-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Pavia Rasher', 'Hooker', '2018-03-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cherilyn Flatt', 'Clarendon', '2015-02-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Travus Shirrell', '8th', '2021-04-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Omero Goodier', 'Anderson', '2019-12-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marrissa Moss', 'Golf View', '2016-03-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fernandina Trewin', 'Westend', '2011-05-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vera Harbach', 'Memorial', '2001-06-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tiffanie Poat', 'Garrison', '2021-06-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Heall Earlam', 'Eagan', '2009-02-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carrol Sandeland', 'Arizona', '2006-04-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Earle Wallington', 'Birchwood', '2001-01-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rob Condit', 'Superior', '2006-06-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Abbi Blincoe', 'Haas', '2001-01-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Trumann Addekin', 'Roth', '2015-05-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nikaniki Alecock', 'Nobel', '2016-07-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fabio Boshard', 'Arrowood', '2013-09-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Debee Karpinski', 'Sundown', '2009-05-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Harlan Richter', 'Shasta', '2002-02-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elli Handasyde', 'Karstens', '2015-07-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tracie Dall', 'Crowley', '2004-11-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Milt Ashburne', 'Holmberg', '2013-10-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mervin Tother', 'Mcguire', '2007-07-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cad Dowdeswell', 'Green Ridge', '2009-08-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Andeee Gwyneth', 'Debra', '2020-10-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nelia Wortley', '3rd', '2016-04-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Juieta Edrich', 'Loftsgordon', '2013-07-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Talbert Riba', 'Sherman', '2001-10-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jennie Falla', 'Parkside', '2019-09-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marcellina Lowres', 'Old Gate', '2006-04-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Conrad Ralph', 'Laurel', '2006-06-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('My Dymott', 'Tennessee', '2006-09-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Emmey Pischel', 'Sullivan', '2020-01-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dion Huson', 'Almo', '2017-02-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Michale Allcroft', 'Main', '2001-09-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bowie Johanning', 'Southridge', '2022-07-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Temple Reynolds', 'Cody', '2021-01-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karalynn Becke', 'Brentwood', '2016-12-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Valentina Bockler', 'Delaware', '2013-12-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Eyde Brizland', 'Waywood', '2006-03-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Padget Larrosa', 'Bobwhite', '2016-11-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sharia Battman', 'Roxbury', '2003-10-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gabi Jedryka', 'Towne', '2018-11-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aline Linn', 'Pierstorff', '2000-05-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jacky Sommerling', 'Kipling', '2019-02-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Peterus Aglione', 'Daystar', '2023-03-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carmencita McGillacoell', 'Fisk', '2005-10-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tobiah Ankers', 'Elka', '2005-02-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Deonne Reignard', 'Delladonna', '2008-08-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kennith Sandcroft', 'Lighthouse Bay', '2011-02-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brendis Daniello', 'Springview', '2016-03-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ettore Goodlake', 'Grasskamp', '2004-10-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dinny Negus', 'Waywood', '2021-03-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Elliott Cyson', 'Muir', '2012-12-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Loutitia Rowbottom', 'Walton', '2003-12-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kial Janacek', 'Oriole', '2013-09-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maribel Surridge', 'Cardinal', '2005-05-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kyla Iacovino', 'Russell', '2020-07-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mercy Arthan', 'Oxford', '2005-10-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Marlie Cabane', 'Dryden', '2019-01-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leroi Aird', 'Onsgard', '2004-07-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Vivien Hamblyn', 'Arapahoe', '2009-09-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Clarence Dressel', 'Killdeer', '2015-04-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Phoebe Sheerman', 'Shoshone', '2007-11-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Giraud Ivancevic', 'Dryden', '2006-04-20');
