insert into tren (modelo, capacidad) values ('Probe', 1);
insert into tren (modelo, capacidad) values ('Continental', 2);
insert into tren (modelo, capacidad) values ('Protege', 3);
insert into tren (modelo, capacidad) values ('E-Series', 4);
insert into tren (modelo, capacidad) values ('Malibu', 5);
insert into tren (modelo, capacidad) values ('Focus', 6);
insert into tren (modelo, capacidad) values ('Roadrunner', 7);
insert into tren (modelo, capacidad) values ('VehiCROSS', 8);
insert into tren (modelo, capacidad) values ('Bonneville', 9);
insert into tren (modelo, capacidad) values ('B-Series', 10);
insert into tren (modelo, capacidad) values ('Integra', 11);
insert into tren (modelo, capacidad) values ('Titan', 12);
insert into tren (modelo, capacidad) values ('Century', 13);
insert into tren (modelo, capacidad) values ('NSX', 14);
insert into tren (modelo, capacidad) values ('Lumina', 15);
insert into tren (modelo, capacidad) values ('Defender 90', 16);
insert into tren (modelo, capacidad) values ('Karif', 17);
insert into tren (modelo, capacidad) values ('GTO', 18);
insert into tren (modelo, capacidad) values ('F350', 19);
insert into tren (modelo, capacidad) values ('Mirage', 20);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 21);
insert into tren (modelo, capacidad) values ('Continental GT', 22);
insert into tren (modelo, capacidad) values ('Silverado 3500', 23);
insert into tren (modelo, capacidad) values ('5 Series', 24);
insert into tren (modelo, capacidad) values ('Suburban 1500', 25);
insert into tren (modelo, capacidad) values ('Tacoma', 26);
insert into tren (modelo, capacidad) values ('Bravada', 27);
insert into tren (modelo, capacidad) values ('Yukon XL 1500', 28);
insert into tren (modelo, capacidad) values ('Grand Prix', 29);
insert into tren (modelo, capacidad) values ('Elise', 30);
insert into tren (modelo, capacidad) values ('Fit', 31);
insert into tren (modelo, capacidad) values ('Corvette', 32);
insert into tren (modelo, capacidad) values ('Corrado', 33);
insert into tren (modelo, capacidad) values ('M-Class', 34);
insert into tren (modelo, capacidad) values ('G', 35);
insert into tren (modelo, capacidad) values ('H1', 36);
insert into tren (modelo, capacidad) values ('Savana', 37);
insert into tren (modelo, capacidad) values ('E250', 38);
insert into tren (modelo, capacidad) values ('Econoline E250', 39);
insert into tren (modelo, capacidad) values ('Sierra 1500', 40);
insert into tren (modelo, capacidad) values ('Town & Country', 41);
insert into tren (modelo, capacidad) values ('Focus ST', 42);
insert into tren (modelo, capacidad) values ('Quest', 43);
insert into tren (modelo, capacidad) values ('Seville', 44);
insert into tren (modelo, capacidad) values ('Venture', 45);
insert into tren (modelo, capacidad) values ('323', 46);
insert into tren (modelo, capacidad) values ('E-Series', 47);
insert into tren (modelo, capacidad) values ('V70', 48);
insert into tren (modelo, capacidad) values ('Safari', 49);
insert into tren (modelo, capacidad) values ('Tiguan', 50);
insert into tren (modelo, capacidad) values ('Concorde', 51);
insert into tren (modelo, capacidad) values ('SLK-Class', 52);
insert into tren (modelo, capacidad) values ('Lancer', 53);
insert into tren (modelo, capacidad) values ('Galant', 54);
insert into tren (modelo, capacidad) values ('914', 55);
insert into tren (modelo, capacidad) values ('Ram Van 2500', 56);
insert into tren (modelo, capacidad) values ('Century', 57);
insert into tren (modelo, capacidad) values ('Freestar', 58);
insert into tren (modelo, capacidad) values ('Clubman', 59);
insert into tren (modelo, capacidad) values ('Expedition', 60);
insert into tren (modelo, capacidad) values ('Grand Am', 61);
insert into tren (modelo, capacidad) values ('Tacoma Xtra', 62);
insert into tren (modelo, capacidad) values ('Golf', 63);
insert into tren (modelo, capacidad) values ('Passat', 64);
insert into tren (modelo, capacidad) values ('Escort', 65);
insert into tren (modelo, capacidad) values ('Prizm', 66);
insert into tren (modelo, capacidad) values ('Cayman', 67);
insert into tren (modelo, capacidad) values ('Camaro', 68);
insert into tren (modelo, capacidad) values ('Bonneville', 69);
insert into tren (modelo, capacidad) values ('Summit', 70);
insert into tren (modelo, capacidad) values ('LR3', 71);
insert into tren (modelo, capacidad) values ('Miata MX-5', 72);
insert into tren (modelo, capacidad) values ('Cutlass Supreme', 73);
insert into tren (modelo, capacidad) values ('LX', 74);
insert into tren (modelo, capacidad) values ('Taurus', 75);
insert into tren (modelo, capacidad) values ('Pajero', 76);
insert into tren (modelo, capacidad) values ('Breeze', 77);
insert into tren (modelo, capacidad) values ('Impala', 78);
insert into tren (modelo, capacidad) values ('S2000', 79);
insert into tren (modelo, capacidad) values ('Dakota', 80);
insert into tren (modelo, capacidad) values ('Camry', 81);
insert into tren (modelo, capacidad) values ('MX-5', 82);
insert into tren (modelo, capacidad) values ('Club Wagon', 83);
insert into tren (modelo, capacidad) values ('Forester', 84);
insert into tren (modelo, capacidad) values ('LS', 85);
insert into tren (modelo, capacidad) values ('Vitara', 86);
insert into tren (modelo, capacidad) values ('S-Class', 87);
insert into tren (modelo, capacidad) values ('GX', 88);
insert into tren (modelo, capacidad) values ('G35', 89);
insert into tren (modelo, capacidad) values ('FX', 90);
insert into tren (modelo, capacidad) values ('F-Series Super Duty', 91);
insert into tren (modelo, capacidad) values ('Loyale', 92);
insert into tren (modelo, capacidad) values ('Cooper Clubman', 93);
insert into tren (modelo, capacidad) values ('626', 94);
insert into tren (modelo, capacidad) values ('M-Class', 95);
insert into tren (modelo, capacidad) values ('Cutlass', 96);
insert into tren (modelo, capacidad) values ('Riviera', 97);
insert into tren (modelo, capacidad) values ('430', 98);
insert into tren (modelo, capacidad) values ('Corvette', 99);
insert into tren (modelo, capacidad) values ('FX', 100);
